[package]
name = "rust-actions-demo"
version = "0.1.0"
authors = ["Thane Thomson <connect@thanethomson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
